#!/usr/bin/env python3


from subprocess import run
from os import walk
from os.path import join

def walk_rst():
    for root, dirs, files in walk("./"):
        for file in files:
            if file.endswith(".rst"):
                render(file[:-4])

def render(filename):
    run(["rst2html5", filename+".rst", filename+".html", "--no-generator", "--link-stylesheet", "--math-output", "MathJax"])
    run(["rst2s5", "--theme", "small-white", filename+".rst", filename+"-s5/"+filename+".html"])
    run(["rst2odt", filename+".rst", filename+".odt"])
    run(["rst2latex", filename+".rst", filename+".tex"])
    run(["rst2pdf", filename+".rst"])

if __name__ == "__main__":
    walk_rst()

